// constants/permissions.js
module.exports = {
  DOCTOR_PERMISSON: "doctor_permission",
  NURSE_PERMISSON: "nurse_permission",
  RECEPTIONIST_PERMISSON: "receptionist_permission",
  USER_PERMISSON: "user_permission",
  GUEST_PERMISSON: "guest_permission",
  MANAGE_SERVICES: "manage_services",
  VIEW_SERVICES: "view_services",
  MANAGE_DOCTORS: "manage_doctors",
  VIEW_DOCTORS: "view_doctors",
  MANAGE_REVIEWS: "manage_reviews",
  VIEW_REVIEWS: "view_reviews",
  MANAGE_SHORTS: "manage_shorts",
  VIEW_SHORTS: "view_shorts",
  MANAGE_APPOINTMENTS: "manage_appointments",
  VIEW_APPOINTMENTS: "view_appointments",
  MANAGE_USERS: "manage_users",
  VIEW_USERS: "view_users",
  MANAGE_BLOGS: "manage_blogs",
  VIEW_BLOGS: "view_blogs",
  MANAGE_GALLERY: "manage_gallery",
  VIEW_GALLERY: "view_gallery",
};
